#!/usr/bin/env bash
# points: 2
# desc: checkout-api's Pod template names q22-critical and the Pods it is running carry that class's resolved priority
set -uo pipefail
. /banks/_lib/checks.sh

NS=reticulum
DEP=checkout-api
PC=q22-critical

dep=$(kubectl -n "$NS" get deploy "$DEP" -o json 2>/dev/null)

[ -n "$dep" ] || {
  echo "Deployment $DEP not found in Namespace $NS"
  show_actual text "$(kubectl -n "$NS" get deploy 2>/dev/null)"
  show_why "This check reads the Deployment $DEP in Namespace $NS, and the pane above lists what that Namespace actually holds. The class has to be named in THIS Deployment's Pod template: a second Deployment created beside it under another name, or bare Pods created at the new priority by hand, are invisible here and are not what was asked for."
  exit 1
}

replicas=$(printf '%s' "$dep" | jq -r '.spec.replicas // 1' 2>/dev/null)
case ${replicas:-} in
  ''|*[!0-9]*) replicas=1 ;;
esac

named=$(printf '%s' "$dep" \
  | jq -r '.spec.template.spec.priorityClassName // "<none>"' 2>/dev/null)

# The class's own value, resolved from the API rather than assumed: the number
# the candidate chose is theirs, and this criterion only asks whether the Pods
# ended up carrying it.
want=$(kubectl get priorityclass "$PC" -o jsonpath='{.value}' 2>/dev/null)
case ${want:-} in
  ''|*[!0-9]*) want='' ;;
esac

# The Deployment's own selector rather than a hard-coded label, so an answer
# that deleted and recreated checkout-api is still graded on its own Pods.
sel=$(printf '%s' "$dep" \
  | jq -r '[ (.spec.selector.matchLabels // {}) | to_entries[] | "\(.key)=\(.value)" ] | join(",")' 2>/dev/null)

pods=''
if [ -n "$sel" ]; then
  pods=$(kubectl -n "$NS" get pod -l "$sel" -o json 2>/dev/null)
fi

# Pods counted by the class they were admitted with, never by name: Pod names
# are generated by the ReplicaSet and change under every rollout, so they say
# nothing about the answer. Terminating Pods are excluded — the tail of a
# rollout is not a wrong answer.
by_class=$(printf '%s' "${pods:-null}" | jq -c '
  [ .items[]?
    | select(.metadata.deletionTimestamp == null)
    | (.spec.priorityClassName // "<none>")
      + " (priority " + ((.spec.priority // 0) | tostring) + ")" ]
  | reduce .[] as $k ({}; .[$k] = ((.[$k] // 0) + 1))' 2>/dev/null)

# jq answers nothing at all when kubectl handed it nothing at all, and a count
# read into arithmetic has to be a number either way.
count_or_zero() {
  case ${1:-} in
    ''|*[!0-9]*) printf '0' ;;
    *) printf '%s' "$1" ;;
  esac
}

# The class's value is compared as a string so that an empty one — the class
# does not exist — can be stood in for by a token no priority will ever equal,
# rather than by a number that might accidentally match.
here=$(printf '%s' "${pods:-null}" | jq --arg pc "$PC" --arg w "${want:-none}" '
  [ .items[]?
    | select(.metadata.deletionTimestamp == null)
    | select((.spec.priorityClassName // "") == $pc)
    | select(((.spec.priority // 0) | tostring) == $w) ] | length' 2>/dev/null)

away=$(printf '%s' "${pods:-null}" | jq --arg pc "$PC" --arg w "${want:-none}" '
  [ .items[]?
    | select(.metadata.deletionTimestamp == null)
    | select((.spec.priorityClassName // "") != $pc
             or ((.spec.priority // 0) | tostring) != $w) ] | length' 2>/dev/null)

here=$(count_or_zero "$here")
away=$(count_or_zero "$away")

evidence() {
  show_actual json "$(printf '{"pod template priorityClassName": "%s", "value of %s": "%s", "running Pods by class": %s, "replicas": %s}' \
    "$named" "$PC" "${want:-<the class does not exist>}" "${by_class:-null}" "$replicas")"
  show_why "$1"
}

template_names_it() { [ "$named" = "$PC" ]; }

# The -ge 1 is not redundant with -ge replicas: a Deployment scaled to zero
# would otherwise satisfy "every Pod carries the class" by running none at all.
pods_carry_it() {
  [ -n "$want" ] && [ "$here" -ge 1 ] && [ "$here" -ge "$replicas" ] && [ "$away" -eq 0 ]
}

crit 1 "the Pod template names $PC" \
  "spec.template.spec.priorityClassName is '$named', want $PC" \
  "priorityClassName is a Pod field, and on a Deployment the Pod that matters is the TEMPLATE: the path is spec.template.spec.priorityClassName. A Deployment's own spec has no such field, so a patch that writes one at the top level changes nothing about the Pods whatever the API makes of it. Chasing the live Pods is not the route either — priorityClassName is not one of the handful of Pod fields an update may change, so the edit is rejected, and even if it landed it would die with that Pod because the ReplicaSet builds every replacement from the template again. A patch over spec.template.spec, or kubectl edit on the Deployment, is what rolls a new ReplicaSet." \
  -- template_names_it

crit 1 "the Pods it is running carry that class's priority" \
  "Pods at $PC: $here of $replicas; Pods at another priority: $away" \
  "Naming a class is a request; spec.priority on the Pod is the resolved answer. The Priority admission plugin looks the name up when the Pod is CREATED and writes the class's integer into spec.priority — which is why a Pod created before the class existed keeps whatever it resolved to then, and why a Pod whose template names a class that does not exist is rejected at creation rather than defaulted. Read the pane above for which of the two happened: Pods still sitting at the old class mean the new ReplicaSet never produced any, and 'kubectl -n $NS describe rs' names the reason — 'no PriorityClass with name $PC was found' is the one to expect if the Deployment was patched before the class was created. Once maxUnavailable is 0 the old Pods are deliberately kept until new ones are Ready, so a rollout that never starts looks like a perfectly healthy workload sitting at the wrong priority." \
  -- pods_carry_it

crit_all_passed || evidence "$(crit_why)"
report "$DEP runs at $PC"
