apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lacerta-gateway
  namespace: lacerta
spec:
  gatewayClassName: sim
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: q15-lacerta.sim.local
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: lacerta-tls
        mode: Terminate
