# This library is sourced, never executed, so it rightly has no shebang. Tell
# ShellCheck the dialect it would otherwise have read from one.
# shellcheck shell=bash

milli() {
  case "$1" in
    *m) printf '%s' "${1%m}" ;;
    "") printf '' ;;
    *) awk -v v="$1" 'BEGIN{printf "%d", v * 1000}' ;;
  esac
}

mib() {
  case "$1" in
    *Mi) printf '%s' "${1%Mi}" ;;
    *Gi) awk -v v="${1%Gi}" 'BEGIN{printf "%d", v * 1024}' ;;
    *Ki) awk -v v="${1%Ki}" 'BEGIN{printf "%d", v / 1024}' ;;
    "") printf '' ;;
    *) printf 'x' ;;
  esac
}

mode_decimal() { printf '%d' "$(( 8#${1#0} ))" 2>/dev/null || printf 'x'; }

file_text() {
  [ -f "$1" ] || { printf ''; return; }
  tr -d '\r' < "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | tr -d '\n'
}

file_lines_sorted() {
  [ -f "$1" ] || { printf ''; return; }
  tr -d '\r' < "$1" \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | grep -v '^$' \
    | sort
}

# Does a whitespace-separated list of names contain this exact name?
#
# Use this rather than grep -w for anything kubectl printed. A hyphen is not a
# word character, so grep -w 'agent' matches 'vault-agent' and grep -w
# 'app-tuning' matches 'my-app-tuning' — the second scores a wrong answer as
# correct. Kubernetes names cannot contain glob characters, so splitting on IFS
# is safe here.
has_name() {
  local want=$2 n
  for n in ${1-}; do
    [ "$n" = "$want" ] && return 0
  done
  return 1
}

same_set() {
  [ "$(printf '%s\n' "$1" | grep -v '^$' | sort)" = "$(printf '%s\n' "$2" | grep -v '^$' | sort)" ]
}

contains_kv() {
  printf '%s\n' "$1" \
    | sed -e 's/[[:space:]]*=[[:space:]]*/=/' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | grep -qx -- "$2=$3"
}

contains_pair() {
  printf '%s\n' "$1" \
    | sed -e 's/[[:space:]][[:space:]]*/ /g' -e 's/^ //' -e 's/ $//' \
    | grep -qx -- "$2 $3"   # lint: allow-grep-qx (operating on normalised text)
}

yaml_api_versions() {
  yq -r '.apiVersion' "$1" 2>/dev/null | grep -v '^null$' | sort -u
}

semver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -1)" = "$2" ]; }

# What a lookup found when it found nothing. A name that does not match — a
# container called vault-agent where the question asked for agent — makes
# kubectl and jq alike return nothing, and staying silent then left the
# candidate reading "runAsUser='', want 10001" with no way to see why. Say so
# instead.
ARTIFACT_EMPTY='none — the object, container or field named here does not exist'

_artifact() {
  local body=$3
  case "$(printf '%s' "$body" | tr -d '[:space:]')" in
    ''|null)
      body=$ARTIFACT_EMPTY
      # show_actual degrades to `text`, because a bare sentence tagged `json`
      # is a lie about its own contents. show_pair passes keep-lang instead:
      # its placeholder sits beside an EXPECTED pane in the declared language
      # and the two headings have to read as one comparison.
      [ -n "${4:-}" ] || set -- "$1" text "$body"
      ;;
  esac
  printf '%s %s %s\n%s\n' '---8<--- sim:artifact' "$1" "$2" "$body"
}

show_actual() { _artifact actual "$1" "${2-}"; }

# The names that DO exist, for a message that can name the real problem:
#   no container named 'agent' (found: vault-agent)
# Takes the raw jsonpath list — '{.spec.containers[*].name}' and friends.
name_list() {
  local names
  names=$(printf '%s' "${1-}" | tr -s '[:space:]' ' ' | sed -e 's/^ //' -e 's/ $//')
  [ -n "$names" ] || { printf 'none'; return; }
  printf '%s' "$names" | sed 's/ /, /g'
}

show_expected() {
  [ -f "$2" ] || return 0
  _artifact expected "$1" "$(cat "$2")"
}

# A check's expected document sits beside the check, at <qid>/expected/<name>,
# and the path is derived from the script's own location rather than spelled
# out. A literal "/banks/${BANK:-cka-mock-01}/q15/expected/..." names a bank to
# fall back to — the wrong one for every bank but that one — and repeats the
# qid in a string, which is exactly the copy-paste that goes wrong when a
# question directory is duplicated to start the next question.
#
# tests/check-evidence.sh runs a REWRITTEN copy of a check out of a temp
# directory, so $0 there points at the copy; it exports SIM_CHECK_PATH with the
# real path. Nothing in production sets it — the grader invokes the script at
# its own path (facilitator/internal/evaluate/evaluate.go:95).
expected_dir() {
  local p=${SIM_CHECK_PATH:-$0}
  printf '%s/expected' "$(dirname "$(dirname "$p")")"
}

# Both panes, from one pipeline.
#
# The actual side is the check's own snapshot(); the expected side is the
# document generated by running that same snapshot() against a solved cluster.
# One function feeds both, so "filter both panes identically"
# (docs/bank-spec.md) stops being something an author has to remember and
# becomes the only way to write it.
show_pair() {
  _artifact actual "$1" "$(snapshot)" keep-lang
  show_expected "$1" "$(expected_dir)/$2"
}

show_why() { _artifact why text "$1"; }

# --------------------------------------------------------------- scored checks
#
# A check used to be all-or-nothing: the first gate that failed took every
# point with it, so a Deployment missing one field out of six scored the same
# as one nobody had touched. Criteria split a check's points across the things
# it actually grades.
#
#   crit WEIGHT "what it grades" "what to say when it fails" -- <test command>
#   report
#
# report exits 0 only when every criterion passed, so the check still reads as
# pass/fail; the grader scales the check's `# points:` by the weight earned.
#
# Not everything should be scored. Keep the plain echo + evidence + exit 1 form
# — a GATE — for the three cases where partial credit would be dishonest:
#   * the object does not exist, so the work was not done at all
#   * a name the question pinned is wrong AND could have been fixed by
#     recreating the object
#   * an action the question ruled out was taken
# A gate exits before report runs, which is what makes it score zero.
#
# Never gate on something the candidate cannot undo. An ephemeral container's
# name is permanent once added, so it is matched on what it does instead.
#
# The full shape, which gets the output order right by construction — the grader
# reads everything before the first sentinel as the check's message, so crit
# prints its failure line the moment it happens, ahead of any evidence pane, and
# report emits the tally last:
#
#   crit 1 "runs as uid 10001" "runAsUser='$uid', want 10001" \
#     "runAsUser is the UID the process runs as, overriding the image's USER." \
#     -- [ "$uid" = 10001 ]
#   crit 1 "read-only root filesystem" "readOnlyRootFilesystem='$ro', want true" \
#     "Container-level only; written at Pod level the API rejects it." \
#     -- [ "$ro" = true ]
#   crit_all_passed || evidence "$(crit_why)"
#   report "identity ok"
#
# The criterion carries the LABEL of what it grades and the message carries the
# detail, so they read as a pair rather than repeating each other. The note is
# optional and crit_why returns the one belonging to the FIRST failure — the
# explanation the candidate needs, rather than a digest of all of them.
_CRIT_EARNED=0
_CRIT_TOTAL=0
_CRIT_LINES=''
_CRIT_WHY=''

crit() {
  local weight=$1 desc=$2 msg=$3 why=''
  shift 3
  # -- is mandatory: it is the only thing that tells an optional note apart from
  # the start of the test command. Getting it wrong would silently grade the
  # wrong thing, so say so instead of guessing.
  if [ "${1-}" != "--" ]; then
    why=$1
    shift
  fi
  if [ "${1-}" != "--" ]; then
    printf 'check bug: crit %s needs -- before the test command\n' "$desc" >&2
    _CRIT_TOTAL=$((_CRIT_TOTAL + weight))
    _CRIT_LINES="${_CRIT_LINES}---8<--- sim:criterion fail ${weight} ${desc}
"
    return 1
  fi
  shift

  _CRIT_TOTAL=$((_CRIT_TOTAL + weight))
  if "$@"; then
    _CRIT_EARNED=$((_CRIT_EARNED + weight))
    _CRIT_LINES="${_CRIT_LINES}---8<--- sim:criterion pass ${weight} ${desc}
"
    return 0
  fi

  printf '%s\n' "$msg"
  _CRIT_LINES="${_CRIT_LINES}---8<--- sim:criterion fail ${weight} ${desc}
"
  [ -n "$_CRIT_WHY" ] || _CRIT_WHY=$why
  return 1
}

# The note belonging to the first criterion that failed.
crit_why() { printf '%s' "$_CRIT_WHY"; }

# For a criterion that passes when something does NOT happen. `!` is a shell
# keyword rather than a command, so it cannot be passed through crit's argument
# list — `-- ! reaches metrics` would look for a binary named '!', fail to find
# it, and score the criterion backwards.
#
# Named negate rather than not because the lint that catches an unsourced helper
# looks for the helper's name in a command position, and the standalone word
# "not" appears in 160 places in these scripts' prose.
negate() { ! "$@"; }

# Has every criterion so far passed? Guards the evidence pane, which is only
# worth attaching to a failure.
crit_all_passed() { [ "$_CRIT_EARNED" -eq "$_CRIT_TOTAL" ]; }

# report [message-when-everything-passed]
#
# The message goes out ahead of the sentinels so it lands in the check's message
# rather than inside an artifact. On failure the message is already there: crit
# printed each failure as it happened.
report() {
  if crit_all_passed && [ -n "${1-}" ]; then
    printf '%s\n' "$1"
  fi
  printf '%s' "$_CRIT_LINES"
  crit_all_passed
}

k8s_clean() {
  yq '(., (select(has("items")) | .items[])) |= (
        del(.metadata.managedFields, .metadata.creationTimestamp, .metadata.resourceVersion,
            .metadata.uid, .metadata.generation, .status,
            .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration")
        | del(.spec.clusterIP  | select(. != "None"))
        | del(.spec.clusterIPs | select(.[0] != "None"))
        | del(.spec.internalTrafficPolicy | select(. == "Cluster"))
        | del(.spec.externalTrafficPolicy | select(. == "Cluster"))
        | del(.spec.sessionAffinity       | select(. == "None"))
        | del(.spec.ipFamilyPolicy        | select(. == "SingleStack"))
        | del(.spec.ipFamilies            | select(length == 1 and .[0] == "IPv4"))
        | del(.metadata.annotations | select(length == 0))
        | del(.metadata | select(length == 0)))' - 2>/dev/null
}
