{{- if include "kubestronaut-sim.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubestronaut-sim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubestronaut-sim.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.hub.secret.cookieKey }}
  COOKIE_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.hub.secret.githubClientID }}
  GITHUB_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.hub.secret.githubClientSecret }}
  GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
