apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubestronaut-sim.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubestronaut-sim.labels" . | nindent 4 }}
