#!/usr/bin/env bash
# points: 3
# desc: every batch-runner Pod runs on sim-worker2, and web-frontend is still there with none of its Pods on it
set -uo pipefail
. /banks/_lib/checks.sh

NS=octans
NODE=sim-worker2
DEP=batch-runner
OTHER=web-frontend

dep=$(kubectl -n "$NS" get deploy "$DEP" -o json 2>/dev/null \
  | jq '{name: (.metadata.name // null),
         replicas: (.spec.replicas // 1),
         selector: (.spec.selector.matchLabels // {})}' 2>/dev/null)

name=$(printf '%s' "${dep:-null}" | jq -r '.name // ""' 2>/dev/null)
replicas=$(printf '%s' "${dep:-null}" | jq -r '.replicas // 1' 2>/dev/null)
case ${replicas:-} in
  ''|*[!0-9]*) replicas=1 ;;
esac

# The Deployment's own selector rather than a hard-coded label: an answer that
# deleted and recreated batch-runner is still the same question, and its Pods
# are whatever its selector says they are.
sel=$(printf '%s' "${dep:-null}" \
  | jq -r '[ (.selector // {}) | to_entries[] | "\(.key)=\(.value)" ] | join(",")' 2>/dev/null)

# jq answers nothing at all when kubectl handed it nothing at all, and a count
# read into arithmetic has to be a number either way.
count_or_zero() {
  case ${1:-} in
    ''|*[!0-9]*) printf '0' ;;
    *) printf '%s' "$1" ;;
  esac
}

# Where the Pods are, counted per node. Names are deliberately not read: they
# are generated by the ReplicaSet and change under every rollout and every
# restart of the environment, so they would make this check's verdict depend on
# something the candidate never chose. spec.nodeName is the scheduler's
# decision and survives a down-and-up untouched.
by_node() {
  kubectl -n "$NS" get pod -l "$1" -o json 2>/dev/null | jq -c '
    [ .items[]? | select(.metadata.deletionTimestamp == null)
                | (.spec.nodeName // "<unscheduled>") ]
    | reduce .[] as $n ({}; .[$n] = ((.[$n] // 0) + 1))' 2>/dev/null
}

evidence() {
  show_actual json "$(printf '{"%s Pods by node": %s, "%s Pods by node": %s, "%s replicas": %s}' \
    "$DEP" "${mine:-null}" "$OTHER" "${theirs:-null}" "$DEP" "${replicas:-null}")"
  show_why "$1"
}

mine=''
theirs=''

[ -n "$name" ] || {
  echo "no Deployment $DEP in Namespace $NS"
  show_actual text "$(kubectl -n "$NS" get deploy 2>/dev/null)"
  show_why "This check grades where the Pods of Deployment $DEP in Namespace $NS are running, and the pane above lists the Deployments that Namespace actually holds. Moving the workload by hand — deleting the Deployment and creating bare Pods on the node, or building a second Deployment beside it under another name — is not what was asked and is invisible here: the object named in the question is the object that is read."
  exit 1
}

[ -n "$sel" ] || {
  echo "Deployment $DEP has no selector to find its Pods by"
  show_actual json "${dep:-null}"
  show_why "A Deployment owns the Pods its spec.selector.matchLabels matches, and this check uses that selector to find them rather than assuming a label. An empty selector is not something a live Deployment can have, so this is an environment fault rather than a wrong answer — nothing about the placement is being judged here."
  exit 1
}

mine=$(by_node "$sel")

# Do-no-harm, and a gate rather than a criterion for two reasons: it is true of
# the untouched seed, so scoring it would hand out a point for work nobody did,
# and the harm it guards against is real. The shortest wrong path through this
# question is to give EVERY workload in the Namespace the toleration, at which
# point the reserved node is shared with the web tier and is not reserved at
# all. web-frontend is pinned to sim-worker and can only arrive on the batch
# node if someone moves it.
other=$(kubectl -n "$NS" get deploy "$OTHER" -o json 2>/dev/null \
  | jq '{name: (.metadata.name // null), selector: (.spec.selector.matchLabels // {})}' 2>/dev/null)
other_name=$(printf '%s' "${other:-null}" | jq -r '.name // ""' 2>/dev/null)

[ -n "$other_name" ] || {
  echo "Deployment $OTHER is gone from Namespace $NS"
  evidence "The question asks for $OTHER to be left alone, and deleting it is the largest possible modification. It exists to prove the reservation works: a node dedicated to batch work is one that the web tier does not land on, and with the web tier deleted there is nothing left to demonstrate that. Re-create it — banks/${BANK:-cka-mock-01}/q21/setup.sh holds the manifest it was seeded from, and a reset re-seeds it."
  exit 1
}

other_sel=$(printf '%s' "${other:-null}" \
  | jq -r '[ (.selector // {}) | to_entries[] | "\(.key)=\(.value)" ] | join(",")' 2>/dev/null)
theirs=$(by_node "${other_sel:-app=$OTHER}")

intruders=$(printf '%s' "${theirs:-null}" | jq -r --arg n "$NODE" '(. // {}) | .[$n] // 0' 2>/dev/null)
intruders=$(count_or_zero "$intruders")

[ "$intruders" -eq 0 ] || {
  echo "$intruders $OTHER Pod(s) are running on $NODE, which is reserved for batch work"
  evidence "$NODE was set aside for batch work, so the one workload that may run there is $DEP. A toleration copied onto $OTHER as well — or its hostname pin re-aimed at $NODE — makes the taint stop meaning anything: the node accepts the web tier again and the dedication is gone. Note that the taint alone would never have moved these Pods here, because NoSchedule only decides NEW placements and evicts nothing; something had to change on $OTHER for this to happen. Undo it, and reach $DEP's placement by changing $DEP alone."
  exit 1
}

here=$(printf '%s' "${mine:-null}" | jq -r --arg n "$NODE" '(. // {}) | .[$n] // 0' 2>/dev/null)
away=$(printf '%s' "${mine:-null}" | jq -r --arg n "$NODE" '
  (. // {}) | [ to_entries[] | select(.key != $n and .key != "<unscheduled>") | .value ]
  | add // 0' 2>/dev/null)
here=$(count_or_zero "$here")
away=$(count_or_zero "$away")

landed() { [ "$here" -ge 1 ] && [ "$here" -ge "$replicas" ] && [ "$away" -eq 0 ]; }

crit 3 "every $DEP Pod runs on $NODE" \
  "$DEP Pods on $NODE: $here of $replicas; on other nodes: $away" \
  "This is the behavioural half of the question: not what the Pod template asks for, but where the scheduler actually put the Pods. The two ways it comes out short read differently in the pane above. Pods still on another node mean nothing forced them to move — a NoSchedule taint never evicts what is already running, and neither does a label; the Pods move because editing spec.template rolls out a new ReplicaSet, so an answer that only tainted and labelled the node leaves the old Pods exactly where they were. Pods counted as <unscheduled> mean the opposite: the template now describes a node that does not exist, which is what a leftover hostname pin AND-ed with the batch-label requirement adds up to, or a batch label that was never written onto $NODE. 'kubectl -n $NS get pod -o wide' and the Pending Pods' events name which of the two it is." \
  -- landed

crit_all_passed || evidence "$(crit_why)"
report "$DEP runs on the batch node"
