import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { render, screen, within } from "@testing-library/react";
import { axe } from "vitest-axe";
import { Explain } from "./Explain";
import type { CheckResult, QuestionResult, Results } from "../api";
import { strings } from "../strings";
import { readThemeCss, ruleBody } from "../test/readCss";

// The scan lives here rather than in a11y.test.tsx because this screen's
// riskiest shapes are its data-dependent ones — a <pre> of per-line spans
// carrying sr-only text, and a <figure>/<figcaption> pair per pane — and
// they only exist when a fixture with artifacts is on screen. Same
// options as the suite-wide scan: component-level renders sit outside
// App's <main>, so the page-level region rule is not meaningful.
const AXE_OPTS = { rules: { region: { enabled: false } } } as const;

const check = (over: Partial<CheckResult> & { name: string }): CheckResult => ({
  desc: "Service selects the Deployment's pods",
  points: 2,
  earned: 0,
  passed: false,
  message: "selector is 'app=web', want app=inventory",
  ...over,
});

const task = (over: Partial<QuestionResult> & { id: string }): QuestionResult => ({
  instance: "instance-1",
  domain: "Services and Networking",
  earned: 0,
  total: 5,
  checks: [],
  ...over,
});

const attempt = (questions: QuestionResult[]): Results => ({
  bank: "ckad-mock-01",
  gradedAt: "2026-08-01T09:00:00Z",
  earned: 0,
  total: 0,
  percent: 0,
  passingScore: 66,
  passed: false,
  questions,
});

// The shape q19's 10_service.sh produces: a captured object, an authored
// counterpart generated by running the reference solution, and a prose
// note. Two lines differ and the rest is identical, which is what a real
// k8s_clean pair looks like.
const ACTUAL = "metadata:\n  name: inventory\nspec:\n  selector:\n    app: web\n";
const EXPECTED = "metadata:\n  name: inventory\nspec:\n  selector:\n    app: inventory\n";

const withEvidence = task({
  id: "q19",
  title: "Expose the inventory Deployment",
  earned: 3,
  total: 7,
  verdict: "partial",
  weightPct: 7.4,
  timeSpentSeconds: 521,
  targetSeconds: 360,
  checks: [
    check({
      name: "10_service.sh",
      artifacts: [
        { kind: "actual", lang: "yaml", body: ACTUAL },
        { kind: "expected", lang: "yaml", body: EXPECTED },
        { kind: "why", body: "The selector matches no Pod, so the Service has no endpoints." },
      ],
    }),
  ],
});

function stubSolution(body: unknown = { id: "q19", markdown: "Apply the Service with `kubectl`." }) {
  vi.stubGlobal(
    "fetch",
    vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/solution")) return new Response(JSON.stringify(body), { status: 200 });
      return new Response(JSON.stringify({}), { status: 200 });
    }),
  );
}

const panes = () => [...document.querySelectorAll(".explain-pane")];
const marked = (kind: "is-removed" | "is-added") => [
  ...document.querySelectorAll(`.explain-line.${kind}`),
];

beforeEach(() => stubSolution());
afterEach(() => vi.unstubAllGlobals());

describe("Explain header", () => {
  test("names the task by its position, domain and weight, and titles the screen with it", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    const heading = screen.getByRole("heading", { level: 1 });
    expect(heading).toHaveTextContent("Expose the inventory Deployment");
    // One h1: this screen replaces the results body, so the score
    // screen's own verdict heading is not on the page beside it.
    expect(screen.getAllByRole("heading", { level: 1 })).toHaveLength(1);

    const eyebrow = document.querySelector(".explain-eyebrow");
    expect(eyebrow).toHaveTextContent("Task 1");
    expect(eyebrow).toHaveTextContent("Services and Networking");
    expect(eyebrow).toHaveTextContent("weight 7%");
  });

  // Zero-padded to the total's width, so stepping from task 9 to task 10
  // does not move the title underneath the eyebrow.
  test("pads the task number to the width of the attempt", () => {
    const many = Array.from({ length: 12 }, (_, i) => task({ id: `q${i}` }));
    render(<Explain results={attempt(many)} questionId="q2" />);
    expect(document.querySelector(".explain-eyebrow")).toHaveTextContent("Task 03");
  });

  test("carries the verdict and the points it was measured from", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    const pill = document.querySelector(".explain-verdict");
    expect(pill).toHaveTextContent("PARTIAL");
    expect(pill).toHaveTextContent("3/7");
    // "3/7" alone is ambiguous read aloud between two other mono figures.
    expect(pill).toHaveTextContent("Points:");
  });

  // The figure measures how long the task PANE was open (api.ts). Nothing
  // here may call it time spent or worked.
  test("reports how long the task was open, against its pacing budget", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    const timing = document.querySelector(".explain-timing");
    expect(timing).toHaveTextContent("8m 41s");
    expect(timing).toHaveTextContent("target 6m");
    expect(timing?.textContent).not.toMatch(/spent|worked/i);
  });

  test("drops the timing pill for a result graded before per-task timing existed", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q01" />);
    expect(document.querySelector(".explain-timing")).toBeNull();
  });

  test("falls back to the ssh-able id when the bank ships no title", () => {
    render(<Explain results={attempt([task({ id: "q07" })])} questionId="q07" />);
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent("q07");
  });
});

describe("Explain document panes", () => {
  test("shows what the cluster had beside what was expected", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    expect(panes()).toHaveLength(2);
    expect(panes()[0]).toHaveTextContent(strings.explain.actualTitle);
    expect(panes()[1]).toHaveTextContent(strings.explain.expectedTitle);
    // Both documents render in full, not only their differences.
    expect(panes()[0]).toHaveTextContent("name: inventory");
    expect(panes()[1]).toHaveTextContent("name: inventory");
  });

  // The brief's panes carry a red tint and a green tint and nothing else,
  // which puts the whole meaning of the screen in one channel. The gutter
  // glyph is the channel that survives greyscale, and the sr-only word is
  // the one that survives having no screen at all.
  test("marks a changed line with something other than colour", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    expect(marked("is-removed")).toHaveLength(1);
    expect(marked("is-added")).toHaveLength(1);
    expect(marked("is-removed")[0]).toHaveTextContent("app: web");
    expect(marked("is-removed")[0].textContent).toContain("-");
    expect(marked("is-added")[0]).toHaveTextContent("app: inventory");
    expect(marked("is-added")[0].textContent).toContain("+");
    expect(marked("is-removed")[0]).toHaveTextContent(strings.explain.lineChanged);
  });

  test("names the glyphs, so the marks do not assume diff literacy", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(screen.getByText(strings.explain.diffLegend)).toBeInTheDocument();
  });

  // The lines that match are not marked at all — that is the whole point
  // of computing an LCS rather than zipping the two documents.
  test("leaves the lines the two documents share unmarked", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    const unmarked = [...document.querySelectorAll(".explain-line")].filter(
      (l) => !l.classList.contains("is-removed") && !l.classList.contains("is-added"),
    );
    expect(unmarked.map((l) => l.textContent?.trim())).toContain("metadata:");
  });

  // A check that failed against a capture identical to the expected
  // document failed on something the capture does not contain. Silence
  // there would read as "these agree", which is the wrong lesson.
  test("says so when the two documents match line for line", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q19",
            checks: [
              check({
                name: "10_service.sh",
                artifacts: [
                  { kind: "actual", body: ACTUAL },
                  { kind: "expected", body: ACTUAL },
                ],
              }),
            ],
          }),
        ])}
        questionId="q19"
      />,
    );
    expect(screen.getByText(strings.explain.diffIdentical)).toBeInTheDocument();
    expect(screen.queryByText(strings.explain.diffLegend)).toBeNull();
  });

  // The shape most evidence-bearing checks actually have: q19's
  // 20_reachable.sh and every check with no authored expected/ file.
  test("a capture with no counterpart renders alone, and says what to compare it against", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q19",
            checks: [
              check({
                name: "20_reachable.sh",
                artifacts: [{ kind: "actual", lang: "yaml", body: ACTUAL }],
              }),
            ],
          }),
        ])}
        questionId="q19"
      />,
    );

    expect(panes()).toHaveLength(1);
    expect(panes()[0]).toHaveTextContent(strings.explain.actualTitle);
    expect(screen.getByText(strings.explain.actualOnlyNote)).toBeInTheDocument();
    // Nothing is marked: there is no second document to differ from.
    expect(marked("is-removed")).toHaveLength(0);
    expect(screen.queryByText(strings.explain.diffLegend)).toBeNull();
  });

  // q19 has two checks that each capture something, and they capture
  // different objects — a Service and an EndpointSlice. One heading over
  // four panes would invite reading them as one comparison.
  test("groups the panes under the check that captured them", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q19",
            checks: [
              check({
                name: "10_service.sh",
                desc: "Service selects the Deployment's pods",
                artifacts: [{ kind: "actual", body: ACTUAL }],
              }),
              check({
                name: "20_reachable.sh",
                desc: "Service has ready endpoints",
                artifacts: [{ kind: "actual", body: "items: []\n" }],
              }),
            ],
          }),
        ])}
        questionId="q19"
      />,
    );

    const blocks = [...document.querySelectorAll(".explain-evidence")];
    expect(blocks).toHaveLength(2);
    expect(blocks[0]).toHaveTextContent("Service selects the Deployment's pods");
    expect(blocks[1]).toHaveTextContent("Service has ready endpoints");
    expect(within(blocks[1] as HTMLElement).getByText(/items: \[\]/)).toBeInTheDocument();
  });

  test("renders the check's own prose about why it failed", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(screen.getByText(strings.explain.whyTitle)).toBeInTheDocument();
    expect(screen.getByText(/the Service has no endpoints/)).toBeInTheDocument();
  });
});

describe("Explain without evidence", () => {
  // Twenty of the twenty-two CKAD questions land here. It is not an error
  // and not a gap in the result — it is what the bank's checks chose to
  // emit — and the screen has to be good anyway.
  test("a task whose checks captured nothing is a complete screen, not an empty one", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q01",
            title: "Namespaces & quotas",
            earned: 2,
            checks: [check({ name: "20_quota.sh", desc: "Quota applied", message: "quota missing" })],
          }),
        ])}
        questionId="q01"
      />,
    );

    expect(panes()).toHaveLength(0);
    expect(screen.getByText(strings.explain.noEvidenceTitle)).toBeInTheDocument();
    // The three things it still has, and the copy points at all of them.
    expect(screen.getByText("Quota applied")).toBeInTheDocument();
    expect(screen.getByText("quota missing")).toBeInTheDocument();
    expect(screen.getByText(strings.explain.solutionTitle)).toBeInTheDocument();
  });

  // Artifacts are dropped from checks that PASSED (api.ts), so a
  // full-marks task can never have any. Saying "no captured state" there
  // would report an absence as though something were missing.
  test("a task that scored full marks says there is nothing to explain", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q01",
            title: "Namespaces",
            earned: 5,
            total: 5,
            verdict: "correct",
            checks: [check({ name: "10_ns.sh", desc: "Namespace exists", earned: 5, passed: true })],
          }),
        ])}
        questionId="q01"
      />,
    );

    expect(screen.getByText(strings.explain.correctTitle)).toBeInTheDocument();
    expect(screen.queryByText(strings.explain.noEvidenceTitle)).toBeNull();
    // The solution is still offered: the grader scored the state, not the
    // route taken to it.
    expect(screen.getByText(strings.explain.solutionTitle)).toBeInTheDocument();
  });

  test("a task the grader recorded no checks for says so", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q01" />);
    expect(screen.getByText(strings.explain.checksNone)).toBeInTheDocument();
  });
});

describe("Explain navigation", () => {
  const three = attempt([
    task({ id: "q01", title: "One" }),
    task({ id: "q02", title: "Two" }),
    task({ id: "q03", title: "Three" }),
  ]);

  test("steps to either neighbour from the middle of the attempt", () => {
    render(<Explain results={three} questionId="q02" />);
    expect(screen.getByRole("link", { name: /previous task/i })).toHaveAttribute(
      "href",
      "#/results/q01",
    );
    expect(screen.getByRole("link", { name: /next task/i })).toHaveAttribute(
      "href",
      "#/results/q03",
    );
  });

  // The order is the ATTEMPT's, which is the order the candidate sat the
  // tasks in — never bank order, and never the id's.
  test("labels the steps by position in the attempt", () => {
    render(<Explain results={three} questionId="q02" />);
    expect(screen.getByRole("link", { name: /previous task/i })).toHaveTextContent("Task 1");
    expect(screen.getByRole("link", { name: /next task/i })).toHaveTextContent("Task 3");
  });

  test("draws no previous step at the first task", () => {
    render(<Explain results={three} questionId="q01" />);
    expect(screen.queryByRole("link", { name: /previous task/i })).toBeNull();
    expect(screen.getByRole("link", { name: /next task/i })).toBeInTheDocument();
  });

  test("draws no next step at the last task", () => {
    render(<Explain results={three} questionId="q03" />);
    expect(screen.getByRole("link", { name: /previous task/i })).toBeInTheDocument();
    expect(screen.queryByRole("link", { name: /next task/i })).toBeNull();
  });

  test("a single-task attempt gets no stepper at all", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q01" />);
    expect(document.querySelector(".explain-nav")).toBeNull();
  });

  test("always offers the way back to the table", () => {
    render(<Explain results={three} questionId="q02" />);
    expect(
      screen.getByRole("link", { name: strings.explain.backToResults }),
    ).toHaveAttribute("href", "#/results");
  });
});

describe("Explain unknown task", () => {
  // A bookmark from an earlier draw, or a hand-typed fragment. Whatever
  // it is, it must not leave a blank screen after a two-hour exam.
  test("says the task is not part of this attempt, and keeps the way back", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q99" />);
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      strings.explain.unknownTask,
    );
    expect(
      screen.getByRole("link", { name: strings.explain.backToResults }),
    ).toBeInTheDocument();
  });
});

describe("Explain reference solution", () => {
  // Eagerly, not behind a disclosure: the attempt is over, so there is no
  // answer left to protect, and this screen exists to explain the task.
  test("loads the reference solution without being asked", async () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
  });

  test("reports a solution the facilitator refuses instead of waiting forever", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes("/solution"))
          return new Response(JSON.stringify({ error: "session has not ended" }), { status: 403 });
        return new Response(JSON.stringify({}), { status: 200 });
      }),
    );

    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(await screen.findByText(/session has not ended/)).toBeInTheDocument();
    expect(screen.getByText(/couldn't load the reference solution/i)).toBeInTheDocument();
  });
});

// jsdom has no CSS engine, so these four declarations are invisible to a
// render test and are read off disk instead — the same trick
// styles/layout.test.ts uses, for the same reason: each of them is
// load-bearing rather than cosmetic, and each fails silently.
describe("Explain pane stylesheet", () => {
  test("the document panes stay on the machine palette", async () => {
    const css = await readThemeCss();
    // THE MACHINE IS NOT THE APP. These panes show a cluster, so they are
    // dark in BOTH themes; repointing them at --surface would make the
    // one surface in the product that must not follow the theme follow it.
    expect(ruleBody(css, ".explain-pane-body")).toContain("background: var(--machine-bg)");
  });

  test("a highlighted line spans the whole scroll width, not the visible box", async () => {
    const css = await readThemeCss();
    // A block child of an overflow-x box is only as wide as the visible
    // box, so without this every tint is cut off at the scroll edge and a
    // long line reads as half-changed.
    expect(ruleBody(css, ".explain-pane-body code")).toContain("min-width: 100%");
    expect(ruleBody(css, ".explain-line")).toContain("display: block");
  });

  test("the diff gutter is not part of what a candidate copies out", async () => {
    const css = await readThemeCss();
    // The expected pane is a document people will paste into a file.
    expect(ruleBody(css, ".explain-line-mark")).toContain("user-select: none");
  });
});

describe("Explain accessibility", () => {
  test("the deep dive with both panes and a loaded solution has no violations", async () => {
    const { container } = render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    // Scan it with the solution actually rendered: the shared markdown
    // renderer brings a figure/figcaption code block and a copy button
    // with a dynamic aria-label, which is exactly the shape a nested
    // interactive violation hides in.
    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
    expect(await axe(container, AXE_OPTS)).toHaveNoViolations();
  });

  test("the ordinary task — no evidence at all — has no violations", async () => {
    const { container } = render(
      <Explain
        results={attempt([
          task({ id: "q01", title: "Namespaces", checks: [check({ name: "10_ns.sh" })] }),
        ])}
        questionId="q01"
      />,
    );
    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
    expect(await axe(container, AXE_OPTS)).toHaveNoViolations();
  });
});

describe("Explain for a multiple-choice question", () => {
  const mcq = task({
    id: "k01",
    title: "Which controller reconciles a Deployment?",
    domain: "Kubernetes Fundamentals",
    earned: 0,
    total: 1,
    options: ["kubelet", "the Deployment controller", "kube-proxy"],
    selected: [0],
    correct: [1],
  });

  // An mcq question has no cluster behind it, so it has no captured state
  // to be missing. Reporting "no captured state for this task" there
  // would invent an absence out of a category error.
  test("reviews the answer instead of reporting a cluster it never had", () => {
    render(<Explain results={attempt([mcq])} questionId="k01" />);

    expect(screen.getByText(strings.explain.answerTitle)).toBeInTheDocument();
    expect(screen.getByText("the Deployment controller")).toBeInTheDocument();
    expect(screen.queryByText(strings.explain.noEvidenceTitle)).toBeNull();
    expect(screen.queryByText(strings.explain.checksTitle)).toBeNull();
    expect(panes()).toHaveLength(0);
  });
});
