import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { render, screen, within } from "@testing-library/react";
import { axe } from "vitest-axe";
import { Explain } from "./Explain";
import type { CheckResult, QuestionResult, Results } from "../api";
import { strings } from "../strings";

// The scan lives here rather than in a11y.test.tsx because this screen's
// riskiest shapes are its data-dependent ones — a <pre> of per-line spans
// carrying sr-only text, and a <figure>/<figcaption> pair per pane — and
// they only exist when a fixture with artifacts is on screen. Same
// options as the suite-wide scan: component-level renders sit outside
// App's <main>, so the page-level region rule is not meaningful.
const AXE_OPTS = { rules: { region: { enabled: false } } } as const;

const check = (over: Partial<CheckResult> & { name: string }): CheckResult => ({
  desc: "Service selects the Deployment's pods",
  points: 2,
  earned: 0,
  passed: false,
  message: "selector is 'app=inventory-api', want app=inventory",
  ...over,
});

const task = (over: Partial<QuestionResult> & { id: string }): QuestionResult => ({
  instance: "instance-1",
  domain: "Services and Networking",
  earned: 0,
  total: 5,
  checks: [],
  ...over,
});

const attempt = (questions: QuestionResult[]): Results => ({
  bank: "ckad-mock-01",
  gradedAt: "2026-08-01T09:00:00Z",
  earned: 0,
  total: 0,
  percent: 0,
  passingScore: 66,
  passed: false,
  questions,
});

// The shape q19's 10_service.sh really produces, verified end to end
// against the live cluster: a captured object, an authored counterpart
// generated by running the reference solution, and a prose note. EXACTLY
// TWO LINES DIFFER — the port it forwards to and the label it selects on
// — and everything else matches, because k8s_clean strips the allocated
// clusterIP that would otherwise have shown as a spurious changed line on
// every attempt. This is what the panes are tuned for: a pair of marked
// lines to find inside a manifest, not a wall of highlight.
const ACTUAL =
  "metadata:\n  name: inventory\nspec:\n  ports:\n    - port: 80\n      targetPort: 80\n  selector:\n    app: inventory-api\n";
const EXPECTED =
  "metadata:\n  name: inventory\nspec:\n  ports:\n    - port: 80\n      targetPort: 8080\n  selector:\n    app: inventory\n";

const withEvidence = task({
  id: "q19",
  title: "Expose the inventory Deployment",
  earned: 3,
  total: 7,
  verdict: "partial",
  weightPct: 7.4,
  timeSpentSeconds: 521,
  targetSeconds: 360,
  checks: [
    check({
      name: "10_service.sh",
      artifacts: [
        { kind: "actual", lang: "yaml", body: ACTUAL },
        { kind: "expected", lang: "yaml", body: EXPECTED },
        { kind: "why", body: "The selector matches no Pod, so the Service has no endpoints." },
      ],
    }),
  ],
});

function stubSolution(body: unknown = { id: "q19", markdown: "Apply the Service with `kubectl`." }) {
  vi.stubGlobal(
    "fetch",
    vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/solution")) return new Response(JSON.stringify(body), { status: 200 });
      return new Response(JSON.stringify({}), { status: 200 });
    }),
  );
}

const panes = () => [...document.querySelectorAll(".explain-pane")];
const marked = (kind: "is-removed" | "is-added") => [
  ...document.querySelectorAll(`.explain-line.${kind}`),
];

beforeEach(() => stubSolution());
afterEach(() => vi.unstubAllGlobals());

describe("Explain header", () => {
  test("names the task by its position, domain and weight, and titles the screen with it", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    const heading = screen.getByRole("heading", { level: 1 });
    expect(heading).toHaveTextContent("Expose the inventory Deployment");
    // One h1: this screen replaces the results body, so the score
    // screen's own verdict heading is not on the page beside it.
    expect(screen.getAllByRole("heading", { level: 1 })).toHaveLength(1);

    const eyebrow = document.querySelector(".explain-eyebrow");
    expect(eyebrow).toHaveTextContent("Task 1");
    expect(eyebrow).toHaveTextContent("Services and Networking");
    expect(eyebrow).toHaveTextContent("weight 7%");
  });

  // Zero-padded to the total's width, so stepping from task 9 to task 10
  // does not move the title underneath the eyebrow.
  test("pads the task number to the width of the attempt", () => {
    const many = Array.from({ length: 12 }, (_, i) => task({ id: `q${i}` }));
    render(<Explain results={attempt(many)} questionId="q2" />);
    expect(document.querySelector(".explain-eyebrow")).toHaveTextContent("Task 03");
  });

  test("carries the verdict and the points it was measured from", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    const pill = document.querySelector(".explain-verdict");
    expect(pill).toHaveTextContent("PARTIAL");
    expect(pill).toHaveTextContent("3/7");
    // "3/7" alone is ambiguous read aloud between two other mono figures.
    expect(pill).toHaveTextContent("Points:");
  });

  // The figure measures how long the task PANE was open (api.ts). Nothing
  // here may call it time spent or worked.
  test("reports how long the task was open, against its pacing budget", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    const timing = document.querySelector(".explain-timing");
    expect(timing).toHaveTextContent("8m 41s");
    expect(timing).toHaveTextContent("target 6m");
    expect(timing?.textContent).not.toMatch(/spent|worked/i);
  });

  test("drops the timing pill for a result graded before per-task timing existed", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q01" />);
    expect(document.querySelector(".explain-timing")).toBeNull();
  });

  test("falls back to the ssh-able id when the bank ships no title", () => {
    render(<Explain results={attempt([task({ id: "q07" })])} questionId="q07" />);
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent("q07");
  });
});

describe("Explain document panes", () => {
  test("shows what the cluster had beside what was expected", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    expect(panes()).toHaveLength(2);
    expect(panes()[0]).toHaveTextContent(strings.explain.actualTitle);
    expect(panes()[1]).toHaveTextContent(strings.explain.expectedTitle);
    // Both documents render in full, not only their differences.
    expect(panes()[0]).toHaveTextContent("name: inventory");
    expect(panes()[1]).toHaveTextContent("name: inventory");
  });

  // The brief's panes carry a red tint and a green tint and nothing else,
  // which puts the whole meaning of the screen in one channel. The gutter
  // glyph is the channel that survives greyscale, and the sr-only word is
  // the one that survives having no screen at all.
  test("marks a changed line with something other than colour", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    // Two lines each way, and the six they share are left alone — the
    // whole point of computing an LCS rather than zipping the documents.
    expect(marked("is-removed")).toHaveLength(2);
    expect(marked("is-added")).toHaveLength(2);
    // Asserted on the fragments that appear in ONE document only:
    // "targetPort: 80" is a prefix of "targetPort: 8080" and
    // "app: inventory" a prefix of "app: inventory-api", so a substring
    // match on either would pass against the wrong pane.
    expect(marked("is-removed")[1]).toHaveTextContent("inventory-api");
    expect(marked("is-removed")[0].textContent).toContain("-");
    expect(marked("is-added")[0]).toHaveTextContent("8080");
    expect(marked("is-added")[0].textContent).toContain("+");
    expect(marked("is-removed")[0]).toHaveTextContent(strings.explain.lineChanged);
  });

  test("names the glyphs, so the marks do not assume diff literacy", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(screen.getByText(strings.explain.diffLegend)).toBeInTheDocument();
  });

  // The lines that match are not marked at all — that is the whole point
  // of computing an LCS rather than zipping the two documents.
  test("leaves the lines the two documents share unmarked", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    const unmarked = [...document.querySelectorAll(".explain-line")].filter(
      (l) => !l.classList.contains("is-removed") && !l.classList.contains("is-added"),
    );
    expect(unmarked.map((l) => l.textContent?.trim())).toContain("metadata:");
  });

  // A check that failed against a capture identical to the expected
  // document failed on something the capture does not contain. Silence
  // there would read as "these agree", which is the wrong lesson.
  test("says so when the two documents match line for line", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q19",
            checks: [
              check({
                name: "10_service.sh",
                artifacts: [
                  { kind: "actual", body: ACTUAL },
                  { kind: "expected", body: ACTUAL },
                ],
              }),
            ],
          }),
        ])}
        questionId="q19"
      />,
    );
    expect(screen.getByText(strings.explain.diffIdentical)).toBeInTheDocument();
    expect(screen.queryByText(strings.explain.diffLegend)).toBeNull();
  });

  // The shape most evidence-bearing checks actually have: q19's
  // 20_reachable.sh and every check with no authored expected/ file.
  test("a capture with no counterpart renders alone, and says what to compare it against", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q19",
            checks: [
              check({
                name: "20_reachable.sh",
                artifacts: [{ kind: "actual", lang: "yaml", body: ACTUAL }],
              }),
            ],
          }),
        ])}
        questionId="q19"
      />,
    );

    expect(panes()).toHaveLength(1);
    expect(panes()[0]).toHaveTextContent(strings.explain.actualTitle);
    expect(screen.getByText(strings.explain.actualOnlyNote)).toBeInTheDocument();
    // Nothing is marked: there is no second document to differ from.
    expect(marked("is-removed")).toHaveLength(0);
    expect(screen.queryByText(strings.explain.diffLegend)).toBeNull();
  });

  // q19 has two checks that each capture something, and they capture
  // different objects — a Service and an EndpointSlice. One heading over
  // four panes would invite reading them as one comparison.
  const twoCapturingChecks = attempt([
    task({
      id: "q19",
      checks: [
        check({
          name: "10_service.sh",
          desc: "Service selects the Deployment's pods",
          artifacts: [
            { kind: "actual", body: ACTUAL },
            { kind: "expected", body: EXPECTED },
          ],
        }),
        check({
          name: "20_reachable.sh",
          desc: "Service has ready endpoints",
          artifacts: [
            { kind: "actual", body: "items: []\n" },
            { kind: "expected", body: "items:\n  - name: web\n" },
          ],
        }),
      ],
    }),
  ]);

  test("groups the panes under the check that captured them", () => {
    render(<Explain results={twoCapturingChecks} questionId="q19" />);

    const blocks = [...document.querySelectorAll(".explain-check")];
    expect(blocks).toHaveLength(2);
    expect(blocks[0]).toHaveTextContent("Service selects the Deployment's pods");
    expect(blocks[1]).toHaveTextContent("Service has ready endpoints");
    expect(within(blocks[1] as HTMLElement).getByText(/items: \[\]/)).toBeInTheDocument();
  });

  // The blocks are grouped, not flattened: one section over the two of
  // them, so the four words that used to head every block are said once,
  // in the plural, and the checks keep a heading each.
  test("heads the whole group once instead of every block", () => {
    render(<Explain results={twoCapturingChecks} questionId="q19" />);

    expect(document.querySelectorAll(".explain-evidence")).toHaveLength(1);
    expect(screen.getByText(strings.explain.evidenceTitle(2))).toBeInTheDocument();
    expect(strings.explain.evidenceTitle(2)).not.toBe(strings.explain.evidenceTitle(1));
  });

  // The legend is a key to a notation, and two comparisons on one screen
  // do not need the key twice. getByText is what enforces it: a second
  // copy makes this throw rather than merely look cluttered.
  test("names the glyphs once for the section, however many comparisons it holds", () => {
    render(<Explain results={twoCapturingChecks} questionId="q19" />);

    expect(screen.getByText(strings.explain.diffLegend)).toBeInTheDocument();
    expect(marked("is-removed").length).toBeGreaterThan(1);
  });

  // What stays per-block is what is true of THAT pair rather than of the
  // notation.
  test("keeps a per-comparison note on the comparison it describes", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q19",
            checks: [
              check({
                name: "10_service.sh",
                artifacts: [
                  { kind: "actual", body: ACTUAL },
                  { kind: "expected", body: EXPECTED },
                ],
              }),
              check({ name: "20_reachable.sh", artifacts: [{ kind: "actual", body: ACTUAL }] }),
            ],
          }),
        ])}
        questionId="q19"
      />,
    );

    const blocks = [...document.querySelectorAll(".explain-check")];
    expect(
      within(blocks[1] as HTMLElement).getByText(strings.explain.actualOnlyNote),
    ).toBeInTheDocument();
    expect(within(blocks[0] as HTMLElement).queryByText(strings.explain.actualOnlyNote)).toBeNull();
  });

  test("renders the check's own prose about why it failed", () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(screen.getByText(strings.explain.whyTitle)).toBeInTheDocument();
    expect(screen.getByText(/the Service has no endpoints/)).toBeInTheDocument();
  });
});

describe("Explain without evidence", () => {
  // Twenty of the twenty-two CKAD questions land here. It is not an error
  // and not a gap in the result — it is what the bank's checks chose to
  // emit — and the screen has to be good anyway.
  test("a task whose checks captured nothing is a complete screen, not an empty one", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q01",
            title: "Namespaces & quotas",
            earned: 2,
            checks: [check({ name: "20_quota.sh", desc: "Quota applied", message: "quota missing" })],
          }),
        ])}
        questionId="q01"
      />,
    );

    expect(panes()).toHaveLength(0);
    expect(screen.getByText(strings.explain.noEvidenceTitle)).toBeInTheDocument();
    // The three things it still has, and the copy points at all of them.
    expect(screen.getByText("Quota applied")).toBeInTheDocument();
    expect(screen.getByText("quota missing")).toBeInTheDocument();
    expect(screen.getByText(strings.explain.solutionTitle)).toBeInTheDocument();
  });

  // Artifacts are dropped from checks that PASSED (api.ts), so a
  // full-marks task can never have any. Saying "no captured state" there
  // would report an absence as though something were missing.
  test("a task that scored full marks says there is nothing to explain", () => {
    render(
      <Explain
        results={attempt([
          task({
            id: "q01",
            title: "Namespaces",
            earned: 5,
            total: 5,
            verdict: "correct",
            checks: [check({ name: "10_ns.sh", desc: "Namespace exists", earned: 5, passed: true })],
          }),
        ])}
        questionId="q01"
      />,
    );

    expect(screen.getByText(strings.explain.correctTitle)).toBeInTheDocument();
    expect(screen.queryByText(strings.explain.noEvidenceTitle)).toBeNull();
    // The solution is still offered: the grader scored the state, not the
    // route taken to it.
    expect(screen.getByText(strings.explain.solutionTitle)).toBeInTheDocument();
  });

  test("a task the grader recorded no checks for says so", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q01" />);
    expect(screen.getByText(strings.explain.checksNone)).toBeInTheDocument();
  });
});

describe("Explain navigation", () => {
  const three = attempt([
    task({ id: "q01", title: "One" }),
    task({ id: "q02", title: "Two" }),
    task({ id: "q03", title: "Three" }),
  ]);

  test("steps to either neighbour from the middle of the attempt", () => {
    render(<Explain results={three} questionId="q02" />);
    expect(screen.getByRole("link", { name: /previous task/i })).toHaveAttribute(
      "href",
      "#/results/q01",
    );
    expect(screen.getByRole("link", { name: /next task/i })).toHaveAttribute(
      "href",
      "#/results/q03",
    );
  });

  // The order is the ATTEMPT's, which is the order the candidate sat the
  // tasks in — never bank order, and never the id's.
  test("labels the steps by position in the attempt", () => {
    render(<Explain results={three} questionId="q02" />);
    expect(screen.getByRole("link", { name: /previous task/i })).toHaveTextContent("Task 1");
    expect(screen.getByRole("link", { name: /next task/i })).toHaveTextContent("Task 3");
  });

  test("draws no previous step at the first task", () => {
    render(<Explain results={three} questionId="q01" />);
    expect(screen.queryByRole("link", { name: /previous task/i })).toBeNull();
    expect(screen.getByRole("link", { name: /next task/i })).toBeInTheDocument();
  });

  test("draws no next step at the last task", () => {
    render(<Explain results={three} questionId="q03" />);
    expect(screen.getByRole("link", { name: /previous task/i })).toBeInTheDocument();
    expect(screen.queryByRole("link", { name: /next task/i })).toBeNull();
  });

  test("a single-task attempt gets no stepper at all", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q01" />);
    expect(document.querySelector(".explain-nav")).toBeNull();
  });

  test("always offers the way back to the table", () => {
    render(<Explain results={three} questionId="q02" />);
    expect(
      screen.getByRole("link", { name: strings.explain.backToResults }),
    ).toHaveAttribute("href", "#/results");
  });
});

describe("Explain unknown task", () => {
  // A bookmark from an earlier draw, or a hand-typed fragment. Whatever
  // it is, it must not leave a blank screen after a two-hour exam.
  test("says the task is not part of this attempt, and keeps the way back", () => {
    render(<Explain results={attempt([task({ id: "q01" })])} questionId="q99" />);
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      strings.explain.unknownTask,
    );
    expect(
      screen.getByRole("link", { name: strings.explain.backToResults }),
    ).toBeInTheDocument();
  });
});

describe("Explain reference solution", () => {
  // Eagerly, not behind a disclosure: the attempt is over, so there is no
  // answer left to protect, and this screen exists to explain the task.
  test("loads the reference solution without being asked", async () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
  });

  test("reports a solution the facilitator refuses instead of waiting forever", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes("/solution"))
          return new Response(JSON.stringify({ error: "session has not ended" }), { status: 403 });
        return new Response(JSON.stringify({}), { status: 200 });
      }),
    );

    render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    expect(await screen.findByText(/session has not ended/)).toBeInTheDocument();
    expect(screen.getByText(/couldn't load the reference solution/i)).toBeInTheDocument();
  });
});

describe("Explain upstream documentation", () => {
  const DOC_URL = "https://kubernetes.io/docs/concepts/services-networking/service/";

  test("links out to what the bank attached, and says where each one goes", async () => {
    stubSolution({
      id: "q19",
      markdown: "Apply the Service with `kubectl`.",
      docs: [{ label: "Services, Load Balancing, and Networking", url: DOC_URL }],
    });
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    const link = await screen.findByRole("link", { name: /Load Balancing/ });
    expect(link).toHaveAttribute("href", DOC_URL);
    // It leaves the app for the candidate's OWN browser — the exam
    // desktop sits behind a documentation allowlist proxy and is not
    // where this opens.
    expect(link).toHaveAttribute("target", "_blank");
    expect(link.getAttribute("rel")).toContain("noreferrer");
    expect(link.getAttribute("rel")).toContain("noopener");
    // Two channels for "this leaves the app": the host is printed beside
    // the label for a sighted reader, and the sr-only tail carries the
    // new tab into the accessible name.
    expect(document.querySelector(".explain-doc-host")).toHaveTextContent("kubernetes.io");
    expect(link).toHaveTextContent(strings.explain.docsNewTab);
  });

  // Most questions carry no `docs` at all — populating them is an
  // authoring task the banks have barely started. Nothing is drawn, and
  // that is the deliberate shape rather than a failure to load.
  test("a question with no upstream links simply ends after the solution", async () => {
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
    expect(document.querySelector(".explain-docs")).toBeNull();
    expect(screen.queryByText(strings.explain.docsTitle)).toBeNull();
  });

  test("an empty list reads the same as a missing one", async () => {
    stubSolution({ id: "q19", markdown: "Apply the Service.", docs: [] });
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    expect(await screen.findByText(/Apply the Service/)).toBeInTheDocument();
    expect(document.querySelector(".explain-docs")).toBeNull();
  });

  // An href is one of the few places a string out of a bank file becomes
  // executable. Anything that is not http(s) is dropped rather than
  // rendered inert: a link that visibly does nothing spends the
  // candidate's trust, and one that is not there costs nothing.
  test("drops a link the browser should not follow rather than rendering it", async () => {
    stubSolution({
      id: "q19",
      markdown: "Apply the Service.",
      docs: [
        { label: "Relative", url: "/docs/concepts" },
        { label: "Script", url: `java${"script"}:alert(1)` },
        { label: "Pod lifecycle", url: DOC_URL },
      ],
    });
    render(<Explain results={attempt([withEvidence])} questionId="q19" />);

    expect(await screen.findByText(/Apply the Service/)).toBeInTheDocument();
    expect(document.querySelectorAll(".explain-doc")).toHaveLength(1);
    expect(screen.queryByText("Script")).toBeNull();
    expect(screen.queryByText("Relative")).toBeNull();
  });
});

// The stylesheet assertions this file used to carry now live in
// styles/layout.test.ts, beside every other load-bearing CSS declaration
// in the project. They were written here only because an earlier lane
// boundary put theme.css and layout.test.ts on opposite sides of it.

describe("Explain accessibility", () => {
  test("the deep dive with both panes, a solution and its links has no violations", async () => {
    // The fullest shape the screen has: panes, prose and a docs footer.
    stubSolution({
      id: "q19",
      markdown: "Apply the Service with `kubectl`.",
      docs: [{ label: "Service", url: "https://kubernetes.io/docs/concepts/" }],
    });
    const { container } = render(<Explain results={attempt([withEvidence])} questionId="q19" />);
    // Scan it with the solution actually rendered: the shared markdown
    // renderer brings a figure/figcaption code block and a copy button
    // with a dynamic aria-label, which is exactly the shape a nested
    // interactive violation hides in.
    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
    expect(await axe(container, AXE_OPTS)).toHaveNoViolations();
  });

  test("the ordinary task — no evidence at all — has no violations", async () => {
    const { container } = render(
      <Explain
        results={attempt([
          task({ id: "q01", title: "Namespaces", checks: [check({ name: "10_ns.sh" })] }),
        ])}
        questionId="q01"
      />,
    );
    expect(await screen.findByText(/Apply the Service with/)).toBeInTheDocument();
    expect(await axe(container, AXE_OPTS)).toHaveNoViolations();
  });
});

describe("Explain for a multiple-choice question", () => {
  const mcq = task({
    id: "k01",
    title: "Which controller reconciles a Deployment?",
    domain: "Kubernetes Fundamentals",
    earned: 0,
    total: 1,
    options: ["kubelet", "the Deployment controller", "kube-proxy"],
    selected: [0],
    correct: [1],
  });

  // An mcq question has no cluster behind it, so it has no captured state
  // to be missing. Reporting "no captured state for this task" there
  // would invent an absence out of a category error.
  test("reviews the answer instead of reporting a cluster it never had", () => {
    render(<Explain results={attempt([mcq])} questionId="k01" />);

    expect(screen.getByText(strings.explain.answerTitle)).toBeInTheDocument();
    expect(screen.getByText("the Deployment controller")).toBeInTheDocument();
    expect(screen.queryByText(strings.explain.noEvidenceTitle)).toBeNull();
    expect(screen.queryByText(strings.explain.checksTitle)).toBeNull();
    expect(panes()).toHaveLength(0);
  });
});

// Reading back a stored attempt. The reference solution is part of the
// bank and the bank is in a session Pod, so a saved attempt simply does
// not contain one — and asking anyway is worse than not having it: with a
// session running it would answer from whichever exam is loaded NOW,
// which need not be the exam being reviewed.
describe("a historical attempt", () => {
  test("does not ask a session for the reference solution", async () => {
    const asked: string[] = [];
    vi.stubGlobal(
      "fetch",
      vi.fn(async (input: RequestInfo | URL) => {
        asked.push(String(input));
        return new Response(JSON.stringify({}), { status: 200 });
      }),
    );

    render(<Explain results={attempt([withEvidence])} questionId="q19" live={false} />);

    await screen.findByRole("heading", { level: 1 });
    expect(asked.filter((url) => url.includes("/solution"))).toHaveLength(0);
  });

  test("says where reference solutions live, and does not report an error", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({}), { status: 200 })));

    render(<Explain results={attempt([withEvidence])} questionId="q19" live={false} />);

    expect(await screen.findByText(/Reference solutions live in the exam environment/i)).toBeTruthy();
    expect(document.querySelector(".explain-solution .error-text")).toBeNull();
  });
});

