apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helios-web
  template:
    metadata:
      labels:
        app: helios-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
