apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: lacerta
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: checkout
    release: green
  type: ClusterIP
